"use client"

import type React from "react"
import { useState, useEffect, useRef } from "react"
import type { ComponentData } from "../App"
import { Button } from "./ui/button"
import { Copy, Download, RotateCcw } from "lucide-react"
import { toast } from "sonner"

interface CodeEditorPaneProps {
  components: ComponentData[]
  fileName: string
  fileType: string
}

export function CodeEditorPane({ components, fileName, fileType }: CodeEditorPaneProps) {
  const [code, setCode] = useState("")
  const [isEditing, setIsEditing] = useState(false)
  const textareaRef = useRef<HTMLTextAreaElement>(null)
  const highlightRef = useRef<HTMLPreElement>(null)

  useEffect(() => {
    setCode(generateCode())
  }, [components, fileName])

  const generateCode = () => {
    const extension = fileName.split(".").pop()?.toLowerCase()

    switch (extension) {
      case "html":
        return generateHTML()
      case "css":
        return generateCSS()
      case "js":
        return generateJS()
      case "php":
        return generatePHP()
      case "sql":
        return generateSQL()
      default:
        return `// ${fileName}\n// Generated by FullDev AI\n`
    }
  }

  const generateHTML = () => {
    const componentToHTML = (component: ComponentData): string => {
      const { type, props } = component

      switch (type) {
        case "text":
          return `    <p class="text-component">${props.content || "Sample Text"}</p>`
        case "heading":
          return `    <h${props.level || 1} class="heading-component">${props.content || "Heading"}</h${props.level || 1}>`
        case "button":
          return `    <button class="btn btn-${props.variant || "primary"}" type="button">${props.text || "Button"}</button>`
        case "image":
          return `    <img src="${props.src || "https://via.placeholder.com/300x200"}" alt="${props.alt || "Image"}" class="image-component">`
        case "navbar":
          const links = (props.links || ["Home", "About", "Contact"])
            .map((link: string) => `        <a href="#${link.toLowerCase()}" class="nav-link">${link}</a>`)
            .join("\n")
          return `    <nav class="navbar-component">\n      <div class="nav-container">\n        <div class="nav-brand">${props.brand || "Brand"}</div>\n        <div class="nav-links">\n${links}\n        </div>\n      </div>\n    </nav>`
        case "hero":
          return `    <section class="hero-component">\n      <div class="hero-content">\n        <h1 class="hero-title">${props.title || "Welcome"}</h1>\n        <p class="hero-subtitle">${props.subtitle || "Build amazing websites"}</p>\n        <button class="btn btn-primary">Get Started</button>\n      </div>\n    </section>`
        case "footer":
          return `    <footer class="footer-component">\n      <div class="footer-content">\n        <p>${props.copyright || "© 2024 Your Company"}</p>\n      </div>\n    </footer>`
        default:
          return `    <div class="component">${type}</div>`
      }
    }

    const htmlContent = components.map((comp) => componentToHTML(comp)).join("\n\n")

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Generated Website - FullDev AI</title>
  <link rel="stylesheet" href="css/styles.css">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
</head>
<body>
  <div id="app" class="app-container">
${htmlContent || "    <!-- No components added yet -->"}
  </div>
  
  <script src="js/main.js"></script>
</body>
</html>`
  }

  const generateCSS = () => {
    return `/* Generated CSS - FullDev AI Website Builder */

/* === RESET & BASE STYLES === */
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

html {
  font-size: 16px;
  scroll-behavior: smooth;
}

body {
  font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  line-height: 1.6;
  color: #1f2937;
  background-color: #ffffff;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

.app-container {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}

/* === COMPONENT STYLES === */

/* Text Components */
.text-component {
  margin-bottom: 1rem;
  color: inherit;
}

.heading-component {
  margin-bottom: 1.5rem;
  font-weight: 600;
  line-height: 1.3;
}

/* Button Components */
.btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  padding: 0.75rem 1.5rem;
  border: none;
  border-radius: 0.5rem;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s ease-in-out;
}

.btn-primary {
  background-color: #3b82f6;
  color: white;
}

.btn-primary:hover {
  background-color: #2563eb;
  transform: translateY(-1px);
}

/* === RESPONSIVE DESIGN === */
@media (max-width: 768px) {
  .nav-container {
    flex-direction: column;
    gap: 1rem;
  }
}`
  }

  const generateJS = () => {
    return `// Generated JavaScript - FullDev AI Website Builder

document.addEventListener('DOMContentLoaded', function() {
    console.log('🚀 FullDev AI website loaded successfully!');
    
    // Initialize all interactive components
    initializeNavigation();
    initializeForms();
    initializeButtons();
    
    console.log('✅ All components initialized');
});

// === NAVIGATION FUNCTIONALITY ===
function initializeNavigation() {
    const navLinks = document.querySelectorAll('.nav-link');
    
    navLinks.forEach(link => {
        link.addEventListener('click', function(e) {
            const href = this.getAttribute('href');
            
            if (href && href.startsWith('#')) {
                e.preventDefault();
                const targetId = href.substring(1);
                const targetElement = document.getElementById(targetId);
                
                if (targetElement) {
                    targetElement.scrollIntoView({ 
                        behavior: 'smooth',
                        block: 'start'
                    });
                }
            }
        });
    });
}`
  }

  const generatePHP = () => {
    return `<?php
// ${fileName}
// Generated by FullDev AI

require_once 'config.php';
require_once 'database.php';

// Your PHP code here

?>`
  }

  const generateSQL = () => {
    return `-- Database Schema
-- Generated by FullDev AI

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;`
  }

  const copyCode = async () => {
    try {
      await navigator.clipboard.writeText(code)
      toast.success("Code copied to clipboard!")
    } catch (err) {
      toast.error("Failed to copy code")
    }
  }

  const downloadCode = () => {
    const blob = new Blob([code], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = fileName
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    toast.success("File downloaded!")
  }

  const resetCode = () => {
    setCode(generateCode())
    setIsEditing(false)
    toast.success("Code reset to original")
  }

  const handleCodeChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setCode(e.target.value)
    setIsEditing(true)
  }

  const renderLineNumbers = () => {
    const lines = code.split("\n")
    return lines.map((_, index) => (
      <div
        key={index}
        className="text-right pr-4 text-muted-foreground select-none font-mono text-sm line-number"
        style={{ lineHeight: "1.5rem", minHeight: "1.5rem" }}
      >
        {index + 1}
      </div>
    ))
  }

  const highlightSyntax = (code: string, fileType: string) => {
    let highlighted = code
    const extension = fileName.split(".").pop()?.toLowerCase()

    if (extension === "html") {
      // HTML tags
      highlighted = highlighted.replace(/(<\/?)([a-zA-Z][a-zA-Z0-9]*)/g, '<span class="keyword">$1$2</span>')
      highlighted = highlighted.replace(/(>)/g, '<span class="keyword">$1</span>')
      // HTML attributes
      highlighted = highlighted.replace(/\s([a-zA-Z-]+)=/g, ' <span class="type">$1</span>=')
      // Strings
      highlighted = highlighted.replace(/=["']([^"']*)["']/g, '=<span class="string">"$1"</span>')
      // Comments
      highlighted = highlighted.replace(/(<!--)(.*?)(-->)/g, '<span class="comment">$1$2$3</span>')
    } else if (extension === "css") {
      // Selectors
      highlighted = highlighted.replace(/^([.#]?[a-zA-Z0-9_-]+)(\s*{)/gm, '<span class="type">$1</span>$2')
      // Properties
      highlighted = highlighted.replace(/\s+([a-z-]+):/g, '  <span class="function">$1</span>:')
      // Values
      highlighted = highlighted.replace(/:([^;{]+);/g, ': <span class="string">$1</span>;')
      // Comments
      highlighted = highlighted.replace(/(\/\*)(.*?)(\*\/)/gs, '<span class="comment">$1$2$3</span>')
    } else if (extension === "js") {
      // Keywords
      const jsKeywords = [
        "function",
        "const",
        "let",
        "var",
        "if",
        "else",
        "for",
        "while",
        "return",
        "class",
        "new",
        "this",
        "document",
        "console",
      ]
      jsKeywords.forEach((keyword) => {
        const regex = new RegExp(`\\b(${keyword})\\b`, "g")
        highlighted = highlighted.replace(regex, '<span class="keyword">$1</span>')
      })
      // Strings
      highlighted = highlighted.replace(/(['"`])((?:\\.|(?!\1).)*?)\1/g, '<span class="string">$1$2$1</span>')
      // Functions
      highlighted = highlighted.replace(/\b([a-zA-Z_$][a-zA-Z0-9_$]*)\s*\(/g, '<span class="function">$1</span>(')
      // Comments
      highlighted = highlighted.replace(/(\/\/.*$)/gm, '<span class="comment">$1</span>')
      highlighted = highlighted.replace(/(\/\*)(.*?)(\*\/)/gs, '<span class="comment">$1$2$3</span>')
    } else if (extension === "php") {
      // PHP tags
      highlighted = highlighted.replace(/(<\?php|\?>)/g, '<span class="keyword">$1</span>')
      // Keywords
      const phpKeywords = [
        "function",
        "class",
        "public",
        "private",
        "protected",
        "static",
        "const",
        "return",
        "if",
        "else",
        "foreach",
        "while",
        "new",
        "require_once",
        "include",
      ]
      phpKeywords.forEach((keyword) => {
        const regex = new RegExp(`\\b(${keyword})\\b`, "g")
        highlighted = highlighted.replace(regex, '<span class="keyword">$1</span>')
      })
      // Strings
      highlighted = highlighted.replace(/(['"])((?:\\.|(?!\1).)*?)\1/g, '<span class="string">$1$2$1</span>')
      // Comments
      highlighted = highlighted.replace(/(\/\/.*$)/gm, '<span class="comment">$1</span>')
    } else if (extension === "sql") {
      // SQL keywords
      const sqlKeywords = [
        "SELECT",
        "FROM",
        "WHERE",
        "INSERT",
        "UPDATE",
        "DELETE",
        "CREATE",
        "TABLE",
        "DATABASE",
        "INDEX",
        "PRIMARY",
        "KEY",
        "FOREIGN",
        "REFERENCES",
        "NOT",
        "NULL",
        "AUTO_INCREMENT",
        "INT",
        "VARCHAR",
        "TEXT",
        "TIMESTAMP",
        "DEFAULT",
        "CURRENT_TIMESTAMP",
        "ENGINE",
        "CHARSET",
        "COLLATE",
        "IF",
        "EXISTS",
      ]
      sqlKeywords.forEach((keyword) => {
        const regex = new RegExp(`\\b(${keyword})\\b`, "gi")
        highlighted = highlighted.replace(regex, '<span class="keyword">$1</span>')
      })
      // Strings
      highlighted = highlighted.replace(/(['"])((?:\\.|(?!\1).)*?)\1/g, '<span class="string">$1$2$1</span>')
      // Comments
      highlighted = highlighted.replace(/(--.*$)/gm, '<span class="comment">$1</span>')
    }

    return highlighted
  }

  // Escape HTML for rendering
  const escapeHTML = (str: string) => {
    return str.replace(/&/g, "&").replace(/</g, "<").replace(/>/g, ">").replace(/"/g, "&quot;").replace(/'/g, "&#039;")
  }

  const renderHighlightedCode = () => {
    const escaped = escapeHTML(code)
    const highlighted = highlightSyntax(escaped, fileType)
    return { __html: highlighted }
  }

  return (
    <div className="h-full flex flex-col bg-card">
      {/* File Tab Bar */}
      <div className="flex items-center justify-between bg-muted/30 border-b border-border code-tab-bar">
        <div className="flex items-center">
          <div className="px-4 py-2 bg-card border-r border-border text-sm flex items-center gap-2 code-tab active">
            <span className="font-medium text-foreground">{fileName}</span>
            {isEditing && <span className="text-orange-500 text-xs">●</span>}
          </div>
        </div>
        <div className="flex items-center gap-1 px-2">
          <Button variant="ghost" size="sm" onClick={copyCode} className="h-8" title="Copy code">
            <Copy className="w-4 h-4" />
          </Button>
          <Button variant="ghost" size="sm" onClick={downloadCode} className="h-8" title="Download file">
            <Download className="w-4 h-4" />
          </Button>
          {isEditing && (
            <Button variant="ghost" size="sm" onClick={resetCode} className="h-8" title="Reset to original">
              <RotateCcw className="w-4 h-4" />
            </Button>
          )}
        </div>
      </div>

      {/* Code Editor Area with Synchronized Scrolling */}
      <div className="flex-1 flex overflow-auto min-h-0">
        {/* Code Content - Fully Scrollable Container */}
        <div className="flex-1 relative min-w-0 min-h-0 flex">
          {/* Line Numbers */}
          <div className="bg-muted/30 border-r border-border px-2 py-4 flex-shrink-0 sticky left-0 z-10">
            <div className="font-mono text-sm">{renderLineNumbers()}</div>
          </div>

          {/* Code area with proper scrolling */}
          <div className="flex-1 relative min-w-0">
            {/* Syntax-highlighted overlay - now syncs with textarea scroll */}
            <pre
              ref={highlightRef}
              className="absolute inset-0 bg-card text-foreground font-mono text-sm p-4 pointer-events-none whitespace-pre overflow-hidden"
              style={{
                lineHeight: "1.5rem",
                tabSize: 2,
              }}
              dangerouslySetInnerHTML={renderHighlightedCode()}
            />
            {/* Editable textarea - this is what user scrolls */}
            <textarea
              ref={textareaRef}
              value={code}
              onChange={handleCodeChange}
              onScroll={(e) => {
                if (highlightRef.current) {
                  highlightRef.current.scrollTop = e.currentTarget.scrollTop
                  highlightRef.current.scrollLeft = e.currentTarget.scrollLeft
                }
              }}
              className="w-full h-full bg-transparent text-transparent caret-foreground font-mono text-sm p-4 resize-none outline-none overflow-auto relative z-10"
              style={{
                lineHeight: "1.5rem",
                tabSize: 2,
                caretColor: "var(--foreground)",
                scrollbarWidth: "thin",
                scrollbarColor: "rgba(155, 155, 155, 0.8) rgba(0, 0, 0, 0.2)",
              }}
              spellCheck={false}
            />
          </div>
        </div>
      </div>
    </div>
  )
}
