/**
 * Design to CSS Converter
 * Converts component design properties from the design panel into clean, functional CSS
 * This ensures the exported code matches the visual design created in the builder
 */

import type { ComponentData } from "../App"

interface CSSRule {
  selector: string
  properties: Record<string, string>
}

// Convert design properties to valid CSS
const sanitizeValue = (value: any): string => {
  if (value === null || value === undefined || value === "") return ""

  // Handle objects (skip them)
  if (typeof value === "object") return ""

  // Handle numbers that need units
  if (typeof value === "number") {
    // If it looks like a position or size, add px
    if (value > 0 && value < 10000) return `${value}px`
    return String(value)
  }

  const strValue = String(value).trim()

  // Already has units or is a keyword
  if (
    strValue.includes("px") ||
    strValue.includes("%") ||
    strValue.includes("rem") ||
    strValue.includes("em") ||
    strValue.includes("rgba") ||
    strValue.includes("rgb") ||
    strValue.includes("linear-gradient") ||
    strValue.includes("radial-gradient") ||
    strValue.includes("transparent") ||
    strValue.includes("inherit") ||
    strValue.includes("auto") ||
    strValue.includes("none")
  ) {
    return strValue
  }

  return strValue
}

const toKebabCase = (str: string): string => {
  return str
    .replace(/([a-z])([A-Z])/g, "$1-$2")
    .replace(/([A-Z])([A-Z][a-z])/g, "$1-$2")
    .toLowerCase()
}

// Convert component styles to CSS rules
export const componentToCSSRule = (component: ComponentData): CSSRule | null => {
  if (!component.style || Object.keys(component.style).length === 0) {
    return null
  }

  const className = component.props?.className || `component-${component.type}-${component.id}`
  const properties: Record<string, string> = {}
  
  let styleToUse = component.style;

  if (component.props?.enableCustomCss) {
    const visualStylesToStrip = [
      'color', 'backgroundColor', 'background', 'borderColor', 'borderStyle', 
      'borderWidth', 'borderRadius', 'boxShadow', 'fontFamily', 'fontSize', 
      'fontWeight', 'textAlign', 'lineHeight', 'letterSpacing', 'textDecoration',
      'textTransform', 'opacity'
    ];
    
    styleToUse = { ...styleToUse };
    visualStylesToStrip.forEach(styleKey => {
      delete (styleToUse as any)[styleKey];
    });
  }

  Object.entries(styleToUse).forEach(([key, value]) => {
    const cssKey = toKebabCase(key)
    const cssValue = sanitizeValue(value)

    if (cssValue && cssValue.length > 0) {
      properties[cssKey] = cssValue
    }
  })

  if (Object.keys(properties).length === 0) {
    return null
  }

  return {
    selector: `.${className}`,
    properties,
  }
}

// Format CSS rule to string
const formatCSSRule = (rule: CSSRule): string => {
  if (rule.properties._raw) {
    return `${rule.selector}\n${rule.properties._raw}`;
  }

  const props = Object.entries(rule.properties)
    .map(([key, value]) => `  ${key}: ${value};`)
    .join("\n")

  return `${rule.selector} {\n${props}\n}`
}

// Generate complete component-specific CSS
export const generateComponentSpecificCSS = (components: ComponentData[]): string => {
  const rules: CSSRule[] = []

  components.forEach((component) => {
    const rule = componentToCSSRule(component)
    if (rule) {
      rules.push(rule)
    }

    if (component.props?.enableCustomCss && component.props?.customCss) {
      rules.push({
        selector: `/* Custom CSS for ${component.props.elementId || component.id} */\n`,
        properties: { _raw: component.props.customCss }
      })
    }
  })

  if (rules.length === 0) {
    return ""
  }

  return `/* ============================================
   Component-Specific Styles (Auto-generated from Design Panel)
   ============================================ */

${rules.map(formatCSSRule).join("\n\n")}`
}

// Generate CSS for all components with proper organization
export const generateFullDesignCSS = (components: ComponentData[], projectName: string): string => {
  const baseCSS = `/* ============================================
   ${projectName} - Auto-Generated CSS
   Generated by FullDev AI Web Builder
   ============================================ */

/* ============================================
   Reset & Normalize
   ============================================ */
*,
*::before,
*::after {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

html {
  scroll-behavior: smooth;
  font-size: 16px;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
  font-size: 1rem;
  line-height: 1.6;
  color: #333;
  background: #f8fafc;
  overflow-x: hidden;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

/* ============================================
   Page Structure
   ============================================ */
.page-wrapper {
  width: 100%;
  display: flex;
  flex-direction: column;
  min-height: 100vh;
}

.container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 24px;
  width: 100%;
}

/* ============================================
   Base Component Styles
   ============================================ */
.btn,
button {
  display: inline-block;
  padding: 10px 20px;
  border-radius: 8px;
  border: none;
  cursor: pointer;
  font-size: 1rem;
  font-weight: 500;
  transition: all 0.3s ease;
  text-decoration: none;
  text-align: center;
  user-select: none;
}

.btn:active,
button:active {
  transform: scale(0.98);
}

.btn-primary,
.btn.btn-primary {
  background: #2563eb;
  color: white;
}

.btn-primary:hover,
.btn.btn-primary:hover {
  background: #1d4ed8;
  box-shadow: 0 4px 12px rgba(37, 99, 235, 0.3);
}

.btn-secondary,
.btn.btn-secondary {
  background: #64748b;
  color: white;
}

.btn-secondary:hover,
.btn.btn-secondary:hover {
  background: #475569;
}

/* ============================================
   Typography
   ============================================ */
h1, h2, h3, h4, h5, h6 {
  font-weight: 600;
  line-height: 1.2;
  margin-bottom: 1rem;
}

h1 { font-size: clamp(2rem, 5vw, 3.5rem); }
h2 { font-size: clamp(1.75rem, 4vw, 2.5rem); }
h3 { font-size: clamp(1.5rem, 3vw, 2rem); }
h4 { font-size: clamp(1.25rem, 2.5vw, 1.75rem); }

p {
  margin-bottom: 1rem;
}

a {
  color: #2563eb;
  text-decoration: none;
  transition: color 0.2s ease;
}

a:hover {
  color: #1d4ed8;
}

/* ============================================
   Cards
   ============================================ */
.card {
  background: white;
  padding: 24px;
  border-radius: 12px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
  transition: all 0.3s ease;
  border: 1px solid #e2e8f0;
}

.card:hover {
  box-shadow: 0 8px 16px rgba(0, 0, 0, 0.1);
  transform: translateY(-2px);
}

/* ============================================
   Navigation
   ============================================ */
.navbar {
  background: white;
  border-bottom: 1px solid #e5e7eb;
  padding: 16px 24px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.05);
  position: sticky;
  top: 0;
  z-index: 100;
  width: 100%;
  max-width: 1920px;
  margin: 0 auto;
}

.navbar-brand {
  font-size: 1.5rem;
  font-weight: 700;
  color: #1f2937;
}

.navbar-links {
  list-style: none;
  display: flex;
  gap: 32px;
}

.navbar-links a {
  color: #666;
  text-decoration: none;
  transition: color 0.2s ease;
  font-weight: 500;
}

.navbar-links a:hover {
  color: #2563eb;
}

/* ============================================
   Forms
   ============================================ */
.input,
input[type="text"],
input[type="email"],
input[type="password"],
textarea,
select {
  padding: 10px 12px;
  border: 1px solid #d1d5db;
  border-radius: 6px;
  font-size: 1rem;
  font-family: inherit;
  transition: all 0.2s ease;
  width: 100%;
}

.input:focus,
input:focus,
textarea:focus,
select:focus {
  outline: none;
  border-color: #2563eb;
  box-shadow: 0 0 0 3px rgba(37, 99, 235, 0.1);
}

/* ============================================
   Grid
   ============================================ */
.grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: 24px;
  margin: 40px 0;
}

.grid-item {
  padding: 20px;
  background: white;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
}

/* ============================================
   Utility Classes
   ============================================ */
.flex { display: flex; }
.flex-col { flex-direction: column; }
.items-center { align-items: center; }
.justify-center { justify-content: center; }
.justify-between { justify-content: space-between; }

.gap-2 { gap: 8px; }
.gap-4 { gap: 16px; }
.gap-8 { gap: 32px; }

.mt-2 { margin-top: 8px; }
.mt-4 { margin-top: 16px; }
.mt-8 { margin-top: 32px; }

.mb-2 { margin-bottom: 8px; }
.mb-4 { margin-bottom: 16px; }
.mb-8 { margin-bottom: 32px; }

.p-2 { padding: 8px; }
.p-4 { padding: 16px; }
.p-8 { padding: 32px; }

.rounded { border-radius: 8px; }
.rounded-lg { border-radius: 12px; }

.shadow { box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1); }
.shadow-lg { box-shadow: 0 8px 16px rgba(0, 0, 0, 0.1); }

.hidden { display: none; }
.visible { display: block; }

.text-center { text-align: center; }
.text-left { text-align: left; }
.text-right { text-align: right; }

/* ============================================
   Responsive Design
   ============================================ */
@media (max-width: 768px) {
  .container {
    padding: 0 16px;
  }

  .navbar {
    flex-direction: column;
    gap: 16px;
  }

  .navbar-links {
    flex-direction: column;
    gap: 16px;
  }

  .grid {
    grid-template-columns: 1fr;
  }

  h1 { font-size: 2rem; }
  h2 { font-size: 1.5rem; }
  h3 { font-size: 1.25rem; }
}

@media (max-width: 480px) {
  body {
    font-size: 14px;
  }

  .container {
    padding: 0 12px;
  }

  .btn, button {
    width: 100%;
  }

  .card {
    padding: 16px;
  }
}`

  const componentCSS = generateComponentSpecificCSS(components)

  return `${baseCSS}

${componentCSS}`
}
